# Generated by Django 4.2.8 on 2024-06-07 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_ingredient_name_remove_recipe_ingredients_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipeingredient',
            name='calories',
            field=models.IntegerField(null=True, verbose_name='Каллории'),
        ),
        migrations.AddField(
            model_name='recipeingredient',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Цена'),
        ),
    ]
