# Generated by Django 4.2.8 on 2024-06-07 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_recipeingredient_calories_recipeingredient_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipeingredient',
            name='calories',
        ),
        migrations.RemoveField(
            model_name='recipeingredient',
            name='price',
        ),
        migrations.AddField(
            model_name='ingredient',
            name='calories',
            field=models.IntegerField(null=True, verbose_name='Каллории'),
        ),
        migrations.AddField(
            model_name='ingredient',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True, verbose_name='Цена'),
        ),
    ]
