# Generated by Django 4.2.8 on 2024-06-08 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_remove_recipeingredient_calories_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredient',
            name='wight',
            field=models.IntegerField(null=True, verbose_name='Вес'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='recipes/%Y/%m/%d/', verbose_name='Картинка к блюду'),
        ),
    ]
